# MkDocs

site_name: 'WildBeast Documentation'
site_author: 'TheSharks'
site_url: 'https://docs.thesharks.xyz'

repo_name: 'TheSharks/WildBeast'
repo_url: 'https://github.com/TheSharks/WildBeast'
edit_uri: edit/master/docs/

copyright: 'Copyright © 2016-2018 TheSharks. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'

nav:
  - Home: 'index.md'
  - Migrating v4 => v6: migrating.md
  - Commands:
    - Command reference: 'commands.md'
    - Custom commands: 'custom_commands.md'
    - Legacy custom commands: 'legacy_custom_commands.md'
  - Installation:
    - Windows installation: 'install_windows.md'
    - Linux installation: 'install_linux.md'
    - Decoupling from Docker: 'decoupling.md'
    - Minimal setup: 'minimal_setup.md'

theme: 'material'

# MkDocs-Material

extra:
  feature:
    tabs: true
  logo: 'img/wb-head-circle.png'
  palette:
    primary: 'indigo'
    accent: 'blue'
  font:
    text: 'Droid Sans'
    font: 'Droid Sans Mono'
  social:
    - type: 'github'
      link: 'https://github.com/TheSharks'

extra_javascript:
  - js/dist/commands.js

extra_css:
  - css/style.css

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true 
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
